#!/usr/bin/env python3
"""ADR-0011 bounded MiniMind pilot: independent evaluation phase.

This is the evaluation-phase runner for the ADR-0011 bounded MiniMind
pilot (issue #74) described in
``docs/decisions/0011-minimind-bounded-pilot-plan.md``. It does not
train anything -- the trainer phase already ran and produced a real,
ACCEPTED ``TrainingOutput`` (see that ADR's "Pilot execution result"
amendment section for the full record: run_id, resource usage, final
loss). This script performs the second, independently-gated half of
the pilot: scoring the already-trained artifact through
``run_evaluator_contract`` using ``HFLocalCausalLMEvaluatorAdapter``,
mirroring exactly the wiring ``examples/pilot-adr0006/run_pilot.py``
uses for its own evaluator phase, adapted for MiniMind's checkpoint
shape.

Why this script does not itself call the MiniMind trainer adapter:
ADR-0011's MiniMind checkpoint format is not natively Hugging-Face
loadable (no ``AutoModelForCausalLM``-compatible directory comes out
of a MiniMind training run). Reusing ``HFLocalCausalLMEvaluatorAdapter``
unmodified -- rather than writing a second, MiniMind-specific evaluator
adapter -- requires first converting the trained MiniMind checkpoint
into a shape-compatible HF ``Qwen3ForCausalLM`` representation (weights
renamed/reshaped to match Qwen3's module layout; MiniMind's own
architecture, not Qwen3, is what was actually trained). That conversion
is a measurement-path detail -- it exists so this evaluator adapter can
read the checkpoint's weights, not because the trained model became a
different model -- and is intentionally out-of-band of this script
(``convert_checkpoint.py`` produced ``CONVERTED_MODEL_DIR`` ahead of
time; see the ADR amendment for the conversion bug found and fixed
along the way: the converted config initially omitted
``num_key_value_heads``, defaulting it to Qwen3's own
``num_attention_heads`` instead of MiniMind's actual KV head count).

Per ADR-0011 and mirroring ADR-0006's own discipline: this script
never resolves the EvaluationOutput into an accept/reject/promotion
decision. It confirms zero contamination, scores the held-out set, and
prints/records the result as evidence -- nothing more.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

from held_out_eval import HeldOutExclusionRegistry

from codevolt_mdf.evaluator_contract import (
    EvaluationOutput,
    HeldOutExample,
    HeldOutSet,
    run_evaluator_contract,
)
from codevolt_mdf.hf_local_evaluator_adapter import HFLocalCausalLMEvaluatorAdapter

# --------------------------------------------------------------------------
# ADR-0011 locked evaluation-phase values (see
# docs/decisions/0011-minimind-bounded-pilot-plan.md, "Pilot execution
# result" amendment section for the full trainer-phase record this
# evaluation phase follows on from).
# --------------------------------------------------------------------------

HELD_OUT_PATH = HERE / "held_out.json"
HELD_OUT_PACKAGE_ID = "adr0011-pilot-heldout-v1"
REGISTRY_PATH = HERE / "held_out_exclusion_registry.json"
RUN_ID = "adr0011-pilot-eval-20260920"

# Converted, HF-loadable representation of the already-trained MiniMind
# checkpoint (see module docstring: shape-compatible Qwen3ForCausalLM
# conversion, not a re-training or a different model). Produced ahead
# of time by this pilot's convert_checkpoint.py and committed as
# evidence-adjacent local scratch, not regenerated by this script.
CONVERTED_MODEL_DIR = HERE / "converted_model"


def _load_held_out_set() -> HeldOutSet:
    payload = json.loads(HELD_OUT_PATH.read_text(encoding="utf-8"))
    examples = [
        HeldOutExample(
            example_id=item["example_id"],
            input=item["input"],
            expected=item["expected"],
        )
        for item in payload["examples"]
    ]
    held_out = HeldOutSet.create(payload["package_id"], examples)
    held_out.validate()  # tamper/shape check before anything else
    return held_out


def main() -> int:
    if not CONVERTED_MODEL_DIR.exists():
        print(
            f"FATAL: converted model directory {CONVERTED_MODEL_DIR} does not "
            "exist. Run convert_checkpoint.py against the accepted MiniMind "
            "trainer artifact first (see the ADR-0011 amendment section for "
            "the conversion procedure and the kv-head-count bug it required "
            "fixing)."
        )
        return 1

    scratch_root = HERE / "scratch" / RUN_ID
    scratch_root.mkdir(parents=True, exist_ok=True)

    print("=" * 72)
    print("ADR-0011 bounded MiniMind pilot -- EVALUATOR phase")
    print("(scoring the already-trained, ACCEPTED MiniMind artifact -- via")
    print(" its converted HF-loadable representation -- through")
    print(" run_evaluator_contract, per ADR-0011's independent evaluation")
    print(" wiring requirement)")
    print(f"run_id={RUN_ID}")
    print(f"converted_model_dir={CONVERTED_MODEL_DIR}")
    print("=" * 72)

    held_out = _load_held_out_set()
    registry = HeldOutExclusionRegistry.load(REGISTRY_PATH)
    contaminated = registry.check_held_out_not_trained(held_out.example_ids)
    if contaminated:
        print(f"FATAL: held-out contamination detected pre-flight: {sorted(contaminated)}")
        result: dict[str, Any] = {
            "evaluation_output": None,
            "evaluation_error": f"contaminated_ids={sorted(contaminated)}",
        }
        _write_result(scratch_root, result)
        return 1

    print()
    print("Zero contamination confirmed: none of the held-out example ids")
    print("are registered as train data by any package in the registry.")
    print()

    evaluator = HFLocalCausalLMEvaluatorAdapter()
    evaluation_output = run_evaluator_contract(
        adapter=evaluator,
        artifact_id="artifact-adr0011-pilot-20260920",
        artifact_locator=str(CONVERTED_MODEL_DIR),
        held_out=held_out,
        registry=registry,
        work_dir=scratch_root / "evaluation_work",
    )

    print("EvaluationOutput:")
    print(f"  status          = {evaluation_output.status.value}")
    print(f"  reason          = {evaluation_output.reason}")
    print(f"  package_id      = {evaluation_output.package_id}")
    print(f"  aggregate_score = {evaluation_output.aggregate_score}")
    print(f"  evidence_locator= {evaluation_output.evidence_locator}")
    print(f"  evidence_hash   = {evaluation_output.evidence_hash}")
    if evaluation_output.contaminated_ids:
        print(f"  contaminated_ids= {evaluation_output.contaminated_ids}")
    if evaluation_output.error_class:
        print(f"  error_class     = {evaluation_output.error_class}")
    print()
    print("  Per-example results:")
    for r in evaluation_output.results:
        print(
            f"    {r.example_id}: correct={r.correct} score={r.score} "
            f"raw_output={r.raw_output!r}"
        )

    result = {"evaluation_output": _evaluation_output_to_dict(evaluation_output)}
    _write_result(scratch_root, result)

    print()
    print("=" * 72)
    print("This is a measurement, not a promotion decision. Aggregate score,")
    print("critical-failure review, and any accept/reject/promotion action")
    print("remain separate, later governed steps this script does not")
    print("perform. Generated-text quality at this training scale (40")
    print("examples, 1 epoch) is expected to be low; a low or zero")
    print("aggregate_score here is an honest, useful pilot result, not a")
    print("failure of this script.")
    print("=" * 72)
    return 0


def _evaluation_output_to_dict(output: EvaluationOutput) -> dict[str, Any]:
    return {
        "status": output.status.value,
        "reason": output.reason,
        "artifact_id": output.artifact_id,
        "package_id": output.package_id,
        "aggregate_score": output.aggregate_score,
        "evidence_locator": output.evidence_locator,
        "evidence_hash": output.evidence_hash,
        "error_class": output.error_class,
        "contaminated_ids": list(output.contaminated_ids),
        "results": [
            {
                "example_id": r.example_id,
                "correct": r.correct,
                "score": r.score,
                "raw_output": r.raw_output,
            }
            for r in output.results
        ],
    }


def _write_result(scratch_root: Path, result: dict[str, Any]) -> None:
    out_path = scratch_root / "pilot_result.json"
    out_path.write_text(json.dumps(result, indent=2, sort_keys=True), encoding="utf-8")
    print(f"\nFull machine-readable result written to: {out_path}")


if __name__ == "__main__":
    raise SystemExit(main())
